### ISSUE TITLE
Cant run examples

### ISSUE THREAD

**Issue by amitpatil321** [vzaar/vzaar-api-php#16]
I Just downloaded code from github and added my token and secret in index.php as well as signature.php file but when i run any example i get the same error 

URL : http://localhost/vzaar-api-php/examples/VideoListTest.php
Error : 
Parse error: syntax error, unexpected '[' in /Applications/AMPPS/www/vzaar-api-php/examples/VideoListTest.php on line 7

Any clue why i am getting this error ? Is there anything i am missing ?

**Comment by edjames** [comment]
Hi

Sorry to hear you're having issues. Please could you provide an example of the code you're using so that I can see exactly what you're trying to do.

Thanks.

**Comment by amitpatil321** [comment]
Ok got it resolved, It was mistake at my end. I must say that was very quick reply.

**Comment by edjames** [comment]
Great, let us know if you need any more help.

**Comment by revdan** [comment]
Glad to hear you got it sorted out! We have to take partial blame for any confusion here - the naming of the `tests` and `examples` directories does seem a bit backward, but this is largely because of historical reasons.

Nevertheless I don't see why we shouldn't rename them to something more fitting, so we'll address that in a future update.
